#!/bin/bash

# Copyright 2017 Johns Hopkins University (Shinji Watanabe)
#  Apache 2.0  (http://www.apache.org/licenses/LICENSE-2.0)

. ./path.sh || exit 1;
. ./cmd.sh || exit 1;

# general configuration
backend=pytorch
stage=1        # start from 0 if you need to start from data preparation
stop_stage=100
ngpu=0         # number of gpus ("0" uses cpu, otherwise use gpu)
debugmode=1
dumpdir=dump   # directory to dump full features
N=0            # number of minibatches to be used (mainly for debugging). "0" uses all minibatches.
verbose=0      # verbose option
resume=        # Resume the training from snapshot
seed=1

# feature configuration
do_delta=false

# configuration path
preprocess_config=conf/preprocess.yaml
train_config=conf/tuning//train_multispkr512_trans.yaml
#lm_config=conf/lm.yaml
#decode_config=conf/tuning/decode_rnn_wyz97.yaml #conf/decode.yaml
decode_config=conf/tuning/decode_pytorch_transformer.yaml

init_frontend=
init_asr=
init_from_mdl=

#testing hyperparameters
test_btaps=
test_nmics=

# network architecture
num_spkrs=2
# optimizer
lr=
# WPD related
use_WPD_frontend=True

# rnnlm related
use_wordlm=true     # false means to train/use a character LM
lm_vocabsize=65000  # effective only for word LMs
lm_layers=1         # 2 for character LMs
lm_units=1000       # 650 for character LMs
lm_opt=sgd          # adam for character LMs
lm_sortagrad=0 # Feed samples from shortest to longest ; -1: enabled for all epochs, 0: disabled, other: enabled for 'other' epochs
lm_batchsize=300    # 1024 for character LMs
lm_epochs=20        # number of epochs
lm_patience=3
lm_maxlen=40        # 150 for character LMs
lm_resume=          # specify a snapshot file to resume LM training
lmtag=              # tag for managing LMs

# decoding parameter
lm_weight=1.0
beam_size=30
penalty=0.0
maxlenratio=0.0
minlenratio=0.0
ctc_weight=0.3
recog_model=model.acc.best # set a model to be used for decoding: 'model.acc.best' or 'model.loss.best'
#recog_model=model.loss.best

# data directories (please fill the blanks)
wsj0=xxx            # path to original wsj0 data
wsj1=xxx            # path to original wsj1 data
wsj_full_wav=xxx    # path to wsj root directory (generated by local/convert2wav.sh)
# root directory containing the generated wsj1-2mix data ("2speakers")
wsj_2mix_wav=$PWD/data/wsj1-mix
wsj_2mix_scripts=$PWD/data_simu/1.create-speaker-mixtures
# root directory containing the generated spatialize wsj1-2mix data
# (both "2speakers_anechoic" and "2speakers_reverb")
wsj_2mix_spatialize_wav=$PWD/data/wsj1-mix

# data scheduling
multich_epochs=

# cmvn
stats_file=fbank/tr_spatialized_all/cmvn.ark
apply_uttmvn=false

# exp tag
tag="" # tag for managing experiments.
cmvn_tag="globalcmvn"

. utils/parse_options.sh || exit 1;

# Set bash to 'debug' mode, it will exit on :
# -e 'error', -u 'undefined variable', -o ... 'error in pipeline', -x 'print commands',
set -e
set -u
set -o pipefail

train_set=tr_spatialized_reverb_multich
train_dev=cv_spatialized_reverb_multich
train_test=tt_spatialized_reverb_multich

if [ ${stage} -le 0 ] && [ ${stop_stage} -ge 0 ]; then
    ### Task dependent. You have to make data the following preparation part by yourself.
    ### But you can utilize Kaldi recipes in most cases
    echo "stage 0: Data preparation"
    local/wsj1_2mix_data_prep.sh ${wsj_2mix_wav}/2speakers/wav16k/max ${wsj_2mix_scripts} \
        ${wsj_2mix_spatialize_wav} ${wsj_full_wav} || exit 1;

    ### Also need wsj corpus to prepare language information
    ### This is from Kaldi WSJ recipe
    local/wsj_data_prep.sh ${wsj0}/??-{?,??}.? ${wsj1}/??-{?,??}.?
    local/wsj_format_data.sh
fi


if [ ${stage} -le 1 ] && [ ${stop_stage} -ge 1 ]; then
    ### Task dependent. You have to design training and dev sets by yourself.
    ### But you can utilize Kaldi recipes in most cases
    #echo "stage 1: Feature Generation"
    #fbankdir=fbank
    ## Generate the fbank features; by default 80-dimensional fbanks with pitch on each frame
    #for x in train_si284 test_dev93 test_eval92; do
    #    steps/make_fbank_pitch.sh --cmd "$train_cmd" --nj 10 --write_utt2num_frames true \
    #        data/${x} exp/make_fbank/${x} ${fbankdir}
    #done

    ## compute global CMVN
    #compute-cmvn-stats scp:data/${train_set}/feats.scp data/${train_set}/cmvn.ark

    echo "stage 1: Dump wav files into a HDF5 file"
    false && {
        dump_pcm.sh --cmd "$train_cmd" --nj 32 --filetype "sound.hdf5" --format flac data/${train_set}
        dump_pcm.sh --cmd "$train_cmd" --nj 32 --filetype "sound.hdf5" --format flac data/${train_dev}
        dump_pcm.sh --cmd "$train_cmd" --nj 32 --filetype "sound.hdf5" --format flac data/${train_test}
    }

    for setname in train_si284; do
        <data/${setname}/utt2spk utils/utt2spk_to_spk2utt.pl >data/${setname}/spk2utt
    done
    dump_pcm.sh --cmd "$train_cmd" --nj 32 --filetype "sound.hdf5" --format flac data/train_si284
fi

dict=data/lang_1char/tr_units.txt
nlsyms=data/lang_1char/non_lang_syms.txt

echo "dictionary: ${dict}"
if [ ${stage} -le 2 ] && [ ${stop_stage} -ge 2 ]; then
    ### Task dependent. You have to check non-linguistic symbols used in the corpus.
    echo "stage 2: Dictionary and Json Data Preparation"
    mkdir -p data/lang_1char/

    echo "make a non-linguistic symbol list"
    cut -f 2- data/train_si284/text | tr " " "\n" | sort | uniq | grep "<" > ${nlsyms}
    cat ${nlsyms}

    echo "make a dictionary"
    echo "<unk> 1" > ${dict} # <unk> must be 1, 0 will be used for "blank" in CTC
    text2token.py -s 1 -n 1 -l ${nlsyms} data/train_si284/text | cut -f 2- -d" " | tr " " "\n" \
    | sort | uniq | grep -v -e '^\s*$' | awk '{print $0 " " NR+1}' >> ${dict}

    echo "make json files"
    for setname in ${train_set} ${train_dev} ${train_test}; do
        local/data2json.sh --cmd "${train_cmd}" --nj 30 --num-spkrs 2 \
            --category "multichannel" \
            --preprocess-conf ${preprocess_config} --filetype sound.hdf5 \
            --feat data/${setname}/feats.scp --nlsyms ${nlsyms} \
            --out data/${setname}/data.json data/${setname} ${dict}
    done

    setname=train_si284
    local/data2json.sh --cmd "${train_cmd}" --nj 30 --num-spkrs 1 \
        --category "singlespeaker" \
        --preprocess-conf ${preprocess_config} --filetype sound.hdf5 \
        --feat data/${setname}/feats.scp --nlsyms ${nlsyms} \
        --out data/${setname}/data.json data/${setname} ${dict}

    mkdir -p data/${train_set}_singlespkr
    concatjson.py data/tr_spatialized_reverb_multich/data.json data/train_si284/data.json data/tr_spatialized_anechoic_multich/data.json > data/${train_set}_singlespkr/data.json
fi
train_set=${train_set}_singlespkr

# It takes about one day. If you just want to do end-to-end ASR without LM,
# YOU CAN SKIP this and remove --rnnlm option in the recognition (stage 5)
if [ -z ${lmtag} ]; then
    lmtag=${lm_layers}layer_unit${lm_units}_${lm_opt}_bs${lm_batchsize}
    if [ ${use_wordlm} = true ]; then
        lmtag=${lmtag}_word${lm_vocabsize}
    fi
fi
lmexpname=train_rnnlm_${backend}_${lmtag}
lmexpdir=exp/${lmexpname}
mkdir -p ${lmexpdir}

if [ ${stage} -le 3 ] && [ ${stop_stage} -ge 3 ]; then
    echo "stage 3: LM Preparation"
    
    if [ ${use_wordlm} = true ]; then
        lmdatadir=data/local/wordlm_train
        lmdict=${lmdatadir}/wordlist_${lm_vocabsize}.txt
        mkdir -p ${lmdatadir}
        cut -f 2- -d" " data/${train_set}/text > ${lmdatadir}/train_trans.txt
        zcat ${wsj1}/13-32.1/wsj1/doc/lng_modl/lm_train/np_data/{87,88,89}/*.z \
                | grep -v "<" | tr "[:lower:]" "[:upper:]" > ${lmdatadir}/train_others.txt
        cut -f 2- -d" " data/${train_dev}/text > ${lmdatadir}/valid.txt
        cut -f 2- -d" " data/${train_test}/text > ${lmdatadir}/test.txt
        cat ${lmdatadir}/train_trans.txt ${lmdatadir}/train_others.txt > ${lmdatadir}/train.txt
        text2vocabulary.py -s ${lm_vocabsize} -o ${lmdict} ${lmdatadir}/train.txt
    else
        lmdatadir=data/local/lm_train
        lmdict=${dict}
        mkdir -p ${lmdatadir}
        text2token.py -s 1 -n 1 -l ${nlsyms} data/${train_set}/text \
            | cut -f 2- -d" " > ${lmdatadir}/train_trans.txt
        zcat ${wsj1}/13-32.1/wsj1/doc/lng_modl/lm_train/np_data/{87,88,89}/*.z \
            | grep -v "<" | tr "[:lower:]" "[:upper:]" \
            | text2token.py -n 1 | cut -f 2- -d" " > ${lmdatadir}/train_others.txt
        text2token.py -s 1 -n 1 -l ${nlsyms} data/${train_dev}/text \
            | cut -f 2- -d" " > ${lmdatadir}/valid.txt
        text2token.py -s 1 -n 1 -l ${nlsyms} data/${train_test}/text \
                | cut -f 2- -d" " > ${lmdatadir}/test.txt
        cat ${lmdatadir}/train_trans.txt ${lmdatadir}/train_others.txt > ${lmdatadir}/train.txt
    fi

    # use only 1 gpu
    if [ ${ngpu} -gt 1 ]; then
        echo "LM training does not support multi-gpu. signle gpu will be used."
    fi
    ${cuda_cmd} --gpu ${ngpu} ${lmexpdir}/train.log \
        lm_train.py \
        --ngpu ${ngpu} \
        --backend ${backend} \
        --verbose 1 \
        --outdir ${lmexpdir} \
        --tensorboard-dir tensorboard/${lmexpname} \
        --train-label ${lmdatadir}/train.txt \
        --valid-label ${lmdatadir}/valid.txt \
        --test-label ${lmdatadir}/test.txt \
        --resume ${lm_resume} \
        --layer ${lm_layers} \
        --unit ${lm_units} \
        --opt ${lm_opt} \
        --sortagrad ${lm_sortagrad} \
        --batchsize ${lm_batchsize} \
        --epoch ${lm_epochs} \
        --patience ${lm_patience} \
        --maxlen ${lm_maxlen} \
        --dict ${lmdict}
fi


if [ -z ${tag} ]; then
    if [ -n "$init_from_mdl" ]; then
        expname=seed${seed}_${train_set}_${backend}_$(basename ${train_config%.*})_$(basename ${preprocess_config%.*})_init_from_mdl${lr:+_lr$lr}${use_WPD_frontend:+_wpd}
    else
        expname=seed${seed}_${train_set}_${backend}_$(basename ${train_config%.*})_$(basename ${preprocess_config%.*})${init_frontend:+_init_frontend}${init_asr:+_init_asr}${lr:+_lr$lr}${use_WPD_frontend:+_wpd}
    fi
    if ${do_delta}; then
        expname=${expname}_delta
    fi
    if [ -n "${cmvn_tag}" ]; then
        expname=${expname}_${cmvn_tag}
    fi
else
    expname=${train_set}_${backend}_${tag}
fi
expdir=exp_revb/${expname}${multich_epochs:+_fromE$multich_epochs}_5taps_$(date +"%Y_%m_%d")

mkdir -p ${expdir}

#train_set=train_si284
#train_set=tr_spatialized_reverb_multich
if [ ${stage} -le 4 ] && [ ${stop_stage} -ge 4 ]; then
    echo "stage 4: Network Training"
    train_opts=""
    if [ -n "${stats_file}" ]; then
        train_opts=${train_opts}" --stats-file ${stats_file}"
    fi
    if ${apply_uttmvn}; then
        train_opts=${train_opts}" --apply-uttmvn true"
    fi

	${cuda_cmd} --gpu ${ngpu} ${expdir}/train.log \
        asr_train.py \
        --config ${train_config} \
        --ngpu ${ngpu} \
        --backend ${backend} \
        --outdir ${expdir}/results \
        --tensorboard-dir tensorboard/${expname} \
        --debugmode ${debugmode} \
        --dict ${dict} \
        --debugdir ${expdir} \
        --minibatches ${N} \
        --verbose ${verbose} \
        --resume ${resume} \
        --train-json data/${train_set}/data.json \
        --valid-json data/${train_dev}/data.json \
        --preprocess-conf ${preprocess_config} \
        --num-spkrs ${num_spkrs} \
        --use-WPD-frontend ${use_WPD_frontend} \
        ${init_frontend:+--init-frontend $init_frontend} \
        ${init_asr:+--init-asr $init_asr} \
        ${init_from_mdl:+--init-from-mdl $init_from_mdl} \
        ${seed:+--seed $seed} \
        ${multich_epochs:+--multich-epochs $multich_epochs} \
        ${lr:+--lr $lr}
fi


if [ ${stage} -le 5 ] && [ ${stop_stage} -ge 5 ]; then
    echo "stage 5: Decoding"
    nj=32

    pids=() # initialize pids
    for rtask in ${train_dev} ${train_test}; do
    (
        prefix=""
        if [ -n "${test_nmics}" ]; then
            prefix=${prefix}_${test_nmics}ch
        fi
        if [ -n "${test_btaps}" ]; then
            prefix=${prefix}_${test_btaps}btaps
        fi
        decode_dir=decode${prefix}_${rtask}_$(basename ${decode_config%.*})_${recog_model}_ctcw${ctc_weight}_rnnlm${lm_weight}_${lmtag}

        if [ ${use_wordlm} = true ]; then
            recog_opts="--word-rnnlm ${lmexpdir}/rnnlm.model.best"
        else
            recog_opts="--rnnlm ${lmexpdir}/rnnlm.model.best"
        fi
        if [ ${lm_weight} == 0 ]; then
            recog_opts=""
        fi
        feat_recog_dir=data/${rtask}

        # split data
        splitjson.py --parts ${nj} ${feat_recog_dir}/data.json

        #### use CPU for decoding
        ngpu=0

        ${decode_cmd} JOB=1:${nj} ${expdir}/${decode_dir}/log/decode.JOB.log \
            asr_recog.py \
            --num-spkrs ${num_spkrs} \
            --config ${decode_config} \
            --ngpu ${ngpu} \
            --backend ${backend} \
            --recog-json ${feat_recog_dir}/split${nj}utt/data.JOB.json \
            --result-label ${expdir}/${decode_dir}/data.JOB.json \
            --model ${expdir}/results/${recog_model} \
            ${seed:+--seed $seed} \
            ${use_WPD_frontend:+--use-WPD-frontend $use_WPD_frontend} \
            ${test_btaps:+--test-btaps $test_btaps} \
            ${test_nmics:+--test-nmics $test_nmics} \
            ${lm_weight:+--lm-weight $lm_weight} \
            ${ctc_weight:+--ctc-weight $ctc_weight} \
            ${recog_opts}
        wait

         score_sclite.sh --wer true --nlsyms ${nlsyms} --num_spkrs ${num_spkrs} ${expdir}/${decode_dir} ${dict}

    ) &
    pids+=($!) # store background pids
    done
    i=0; for pid in "${pids[@]}"; do wait ${pid} || ((++i)); done
    [ ${i} -gt 0 ] && echo "$0: ${i} background jobs are failed." && false
    echo "Finished"
    exit 0;
fi
