# network architecture
model-module: espnet.nets.pytorch_backend.e2e_asr_mix_transformer:E2E
# frontend related
btype: transformer
beamformer-time-restricted-window: 30
# encoder related
elayers: 12      # number of recognition encoder layers
eunits: 2048
# decoder related
dlayers: 6
dunits: 2048
# attention related
adim: 256
aheads: 4

# hybrid CTC/attention
mtlalpha: 0.2

# label smoothing
lsm-weight: 0.1

# minibatch related
batch-size: 8
maxlen-in: 500  # if input length  > maxlen-in, batchsize is automatically reduced
maxlen-out: 150 # if output length > maxlen-out, batchsize is automatically reduced

# optimization related
sortagrad: 0 # Feed samples from shortest to longest ; -1: enabled for all epochs, 0: disabled, other: enabled for 'other' epochs
opt: noam
accum-grad: 4
grad-clip: 5
patience: 30
epochs: 100
dropout-rate: 0.1
bdropout-rate: 0.1

# transformer specific setting
backend: pytorch
transformer-input-layer: conv2d     # encoder architecture type
transformer-lr: 0.2
transformer-warmup-steps: 25000
transformer-attn-dropout-rate: 0.0
transformer-length-normalized-loss: false
transformer-init: pytorch

# Report CER & WER
report-cer: false
report-wer: false
