# hybrid CTC/attention
mtlalpha: 0.3

# label smoothing
#lsm-type: ""
lsm-weight: 0.1

# minibatch related
batch-size: 8
#batch-bins: 15000000
#maxlen-in: 800  # if input length  > maxlen-in, batchsize is automatically reduced
#maxlen-out: 800 # if output length > maxlen-out, batchsize is automatically reduced

# optimization related
sortagrad: 0 # Feed samples from shortest to longest ; -1: enabled for all epochs, 0: disabled, other: enabled for 'other' epochs
opt: adam
weight-decay: 0
#accum-grad: 2
#grad-clip: 5
patience: 3
epochs: 100
#dropout-rate: 0.1
#early-stop-criterion: "validation/main/acc"

# scheduled sampling option
#sampling-probability: 0.0

# CMVN
#stats-file: data/train_960/cmvn_80dim.ark #data/train_960/cmvn.ark
apply-uttmvn: True

# reporting
#report-wer: True

# frontend related
btype: blstm
use-frontend: True
use-beamforming-first: False
# beamforming
use-beamformer: True
blayers: 3
bnmask: 6
bunits: 600
bprojs: 600
beamformer-type: mvdr
ref-channel: 0
# WPE
use-wpe: True
use-dnn-mask-for-wpe: True
wpe-taps: 5 #1
